### PR TITLE
Non spatial io

### PR DESCRIPTION
**Pull request by burlen**
* adds support for writing information arrays(those have no geometric/spatial association)
* uses this in the Bayesian AR detector to capture and output parameter table row, and AR count for each row.

### CODE REVIEW

**Comment by taobrienlbl** [comment]
@burlen - I just tested this out.  The test I ran worked nicely and the file contains exactly what I'd expect: nice!

**Comment by burlen** [comment]
> @burlen - I just tested this out. The test I ran worked nicely and the file contains exactly what I'd expect: nice!

@taobrienlbl Thank you for testing this out, glad it is doing what you need! newer  commits add support for reading the data back in, adds a regression test, and fixes some issues that popped up along the way. the regression test depends on #289 so that branch needs to be merged first.

**Comment by burlen** [comment]
failing tests should be resolved by #284

**Comment by burlen** [comment]
no new changes, rebasing from the rebased python_algorithm

**Comment by burlen** [comment]
non new commits, rebased from master, and changed merge target to master

**Pull request merged**
