### PR TITLE
Integrating Breathe into TECA

### PR DESCRIPTION
**Pull request by elbashandy**
I only added Breathe into TECA but haven't used it in the documentation. In order to know how to use it, follow the [Breathe guide](https://breathe.readthedocs.io/en/latest/index.html).

To use Breathe in rst format, it will look something like this:

```rst
.. doxygenclass:: teca_2d_component_area
   :members:
   :protected-members:
   :private-members:
   :undoc-members:
```

To remove the private members from the documentation for example, remove the line that has `:private-members:`

### CODE REVIEW

**Comment by burlen** [comment]
please include the example that you had in the original pr

**Comment by elbashandy** [comment]
@burlen I am not sure I follow which example you are referring to. Are you talking about the extra C++ documentation that I added to the code? for example: commit `3f151c407ac795d5f056926b456afd4522d68e74`. Or are you referring to the framework pages that I added in `01e85023f9aaf268b4c930cc5173f287a33e35a4`?

**Comment by burlen** [comment]
I'm referring to the changes that put some classes in the rtd users guide using breathe. This showed that things were working. I would like you to post a link to rtd showing this pr working as well.

**Comment by elbashandy** [comment]
@burlen I cherry-picked the commit that has the class pages, where each page has breathe covering some of the components:

https://teca.readthedocs.io/en/integrating_breathe/framework/framework.html

Let me know if you are referring to something else.

**Comment by burlen** [comment]
Thanks Abdel! I'll take it from here

**Comment by burlen** [comment]
resolves #610
resolves #609
resolves #608
resolves #607
resolves #606
resolves #605
resolves #604
resolves #603
resolves #602
resolves #594
resolves #592
 
includes a abunch of the work for #595

**Pull request merged**
