### PR TITLE
Removed resnet model dependence

### PR DESCRIPTION
**Pull request by elbashandy**
The deeplab model already represents the whole neural network architecture parameters

### CODE REVIEW

**Comment by burlen** [comment]
does this change anything in relation to binary files needed to be deployed?

**Comment by elbashandy** [comment]
> does this change anything in relation to binary files needed to be deployed?

It shouldn't but because the resnet model wasn't being used at all as it's parameter values were overwritten by the deeplab model values

**Comment by burlen** [comment]
> > does this change anything in relation to binary files needed to be deployed?
> 
> It shouldn't but because the resnet model wasn't being used at all as it's parameter values were overwritten by the deeplab model values
OK, so then if I understand you, the resnet model was never committed into the TECA_data nor to the  TECA_assets repo?

**Comment by elbashandy** [comment]
> > > does this change anything in relation to binary files needed to be deployed?
> > 
> > 
> > It shouldn't but because the resnet model wasn't being used at all as it's parameter values were overwritten by the deeplab model values
> 
> OK, so then if I understand you, the resnet model was never committed into the TECA_data nor to the TECA_assets repo?

Oh no I need to delete those haha. I thought you were talking about the regression tests binary files

**Comment by burlen** [comment]
@elbashandy please remove the uneeded files from the svn repos and don't forget to update the teca_data svn repo test version so that we don't have to pull them down when we test.

**Pull request merged**
