### PR TITLE
more executive generalization

### PR DESCRIPTION
**Pull request by burlen**
* writers use index in file names
* data sources pass index in dataset metadata
* reductions isolate executive controls from pipeline below/above the reduction
* dataset diff mediates between pipeline below and the 2 pipelines above
* a handful of bug fixes and small features

### CODE REVIEW

**Comment by burlen** [comment]
closes #236,#230

**Comment by burlen** [comment]
@taobrienlbl could you help me with a review? this started as a few small features but evolved into a big change to update writers to use the new more general map index keys instead of hard coding for the  time_step key.

**Comment by taobrienlbl** [comment]
@burlen - I've reviewed the best I can, and it looks good over all.  That said, there are a lot of code modifications to parts of TECA where I'm not yet familiar with the purpose of the code.  So I'm not sure how effective my review is.

Also, because there are so many different modifications, I've had a hard time wrapping my head around the implications of all of these changes.

Perhaps, given the scope of this PR, it would make sense to get additional eyes on this; that could help with covering the parts that I'm not able to adequately review.

**Comment by burlen** [comment]
yes, this is a big set of change, and complex. I'm afraid beside myself you know teca internals better than anyone. I understand that this one may not be realistically review-able. I tested on your script and it still worked.

**Pull request merged**
