### PR TITLE
CF Reader and Temporal Reduction Modifications for ARTMIP Averaging

### PR DESCRIPTION
**Pull request by taobrienlbl**
* ~~Fixes potential typecast bug in temporal reduction~~
* Adds option to override time attributes/values even when time variable is specified

### CODE REVIEW

**Comment by taobrienlbl** [comment]
@burlen - could you please review this PR when you get a moment? 

The type coercion in `teca_temporal_reduction.py` is b/c the calendar utils library expects a double for the time variable, but I encountered a dataset in ARTMIP that uses float for the time variable.

The additonal options in the CF reader are because I want to be able to override the time, calendar, and units attributes (b/c some ARTMIP algorithms have bad data stored in the netCDF variables, so I want to force them to what I know they should be).  Prior to this commit, the `teca_cf_reader.set_t_calendar()`, `teca_cf_reader.set_t_units()`, and `teca_cf_reader.set_t_values()` would only have an effect if the time variable was not set (and therefore not read from the netCDF files).  This revision allows overriding these values while still maintaining the mapping between time indices and filenames inferred by the CF reader when the time variable is set.

**Comment by burlen** [comment]
I'll look at it before cob today

**Comment by burlen** [comment]
before going with this solution I'd like to see if we can get SWIG to automatically convert from numpy scalars to C types. And to see if we could template our code to handle either float or double. I need to verify this but I think we already convert integers in the time axis to floating point.

**Comment by burlen** [comment]
have integrated numpy scalars so that SWIG handles them automatically. more work to do

**Comment by burlen** [comment]
moved numpy & single precision floating point axis code to #442. this PR still has the improvements to the CF reader for overriding the time axis values.

**Review by burlen — APPROVED** [review]
these overrides look useful for non CF2 compliant files. I added a commit to integrate with the more recent validation code that checks and alerts for non compliant data and in some cases provides a default.  Things got reordered a bit and I split the calendar and units override such that they are applied separately. Other than that the functionality is as you implemented. If you see any issues with my changes let me know, otherwise please go ahead and merge

**Pull request merged**
