### PR TITLE
Fixed n_steps_iterator class of python version of temporal_reduction

### PR DESCRIPTION
**Pull request by amandasd**

### CODE REVIEW

**Review by burlen — APPROVED** [review]
would you please rebase from develop before merge? thank you!

**Comment by amandasd** [comment]
> would you please rebase from develop before merge? thank you!

@burlen Just to clarify, which one of the 2 options available (create a merge commit; rebase and merge) should I select?

**Comment by taobrienlbl** [comment]
@amandasd - my recommendation would be to do the rebase from the command line (i.e., `git checkout develop; git pull; git checkout python_temporal_reduction; git rebase develop`), do a force-push, then use the 'merge pull request' button once the CI checks complete one last time.  Rebasing usually goes flawlessly, but if there are any conflicts, doing the rebase from the command line gives you much more flexibility.

**Comment by amandasd** [comment]
> @amandasd - my recommendation would be to do the rebase from the command line (i.e., `git checkout develop; git pull; git checkout python_temporal_reduction; git rebase develop`), do a force-push, then use the 'merge pull request' button once the CI checks complete one last time. Rebasing usually goes flawlessly, but if there are any conflicts, doing the rebase from the command line gives you much more flexibility.

I have already done everything you mentioned (i.e., git checkout develop; git pull; git checkout python_temporal_reduction; git rebase develop; git push --force; CI checks). My question is about the 'merge pull request' button. We have two options there: create a merge commit; rebase and merge. Which one should I select? I am asking this because in the test_lapse_rate branch I chose the first one and I remember Travis telling me is wasn't the correct option.

**Comment by burlen** [comment]
@amandasd it all looks good now!

to clarify: we just want to have this (and any other) branch have all the changes from dervelop before merging. That wasn't the case when I made the comment. Travis described how one would do this using the command line (my preference as well). Now that you';ve done that, the github option with the "merge pull request" button that you want is the default "create merge commit".  I guess their "rebase and merge" option might do what we want too, but I haven't experimented with it.

**Pull request merged**
