### PR TITLE
Update ubuntu to 20.04 LTS

### LINKED ISSUE #333: create docker image for Travis CI with latest Ubuntu  release
create docker image for Travis CI with latest Ubuntu  release. 18.04 is ~ 2 yo, especially with Ubuntu because its packages are old to begin with we should stay ahead of our users in testing on new OS releases. When the new image is in place , retire the 18.04 image.

### LINKED ISSUE #393: Use Parallel NetCDF in Ubuntu Travis CI
In the CMake output you will see:
```
-- NetCDF features -- enabled
-- Check NetcCDF for MPI support -- not found
```
The last line should say enabled, parallel CF writer tests will not work without this.

Should be done as a part of #333

### PR DESCRIPTION
**Pull request by elbashandy**
resolves #333 
resolves #393

### CODE REVIEW

**Comment by burlen** [comment]
FYI, I am taking on the ABI flags issue today (See #399)

**Comment by burlen** [comment]
@elbashandy ABI flags issue should be all set now, rebase from develop to get that fix

**Comment by burlen** [comment]
resolves #333 
resolves #393

**Comment by burlen** [comment]
@elbashandy in the future please list the issues that are resolved by the PR in the PR description field. I've added them to this one just now.

**Comment by elbashandy** [comment]
Apologies @burlen I got directed from the emails  to the main reviews that you left.. not the comment that you added here as well.

**Comment by burlen** [comment]
> Apologies @burlen I got directed from the emails to the main reviews that you left.. not the comment that you added here as well.

It's all in the review, there was only 1, and there were no additional comments outside of it.

**Comment by elbashandy** [comment]
Yes I realized what went wrong. I have a habit of going directly to the "Files changed" tab and see what you requested for change. I should focus on the main review -- which is only shown in the comments section. Again @burlen, apologies for wasting your time.

**Comment by elbashandy** [comment]
Rebasing

**Pull request merged**
