### PR TITLE
Fix connected components

### PR DESCRIPTION
**Pull request by taobrienlbl**
Connected components currently counts one too many objects.  Analysis of output meshes indicates that it counts the background as a connected component.  The first commit in this branch adds a test `test/python/test_connected_components_simple.py` demonstrating this on a simple test case.

@burlen - could you please verify that this test is valid and that the failure indeed indicates a bug?

### CODE REVIEW

**Comment by taobrienlbl** [comment]
@burlen - I have pushed a proposed fix: the approach labels the background as -1 and starts counting connected components from -1.

Fixes #404

**Comment by burlen** [comment]
This was by design. It makes things easier to treat the background as a component, it's always assigned label 0. for instance the area calculation calculates the area of the background as well. Should we discuss this over zoom?

**Comment by taobrienlbl** [comment]
After discussing this in detail, here is our initial proposal:
Undo commit 01a7a90 in `cc_fix` branch
Improve documentation about the connected components algorithm (in header and RTD)
Rename metadata variable `number_of_components` to `number_of_labels`
Add simple test to ensure that segmentation works as expected if first value of array is not background
Check whether `ar_count` in `teca_bayesian_ar_detect` is reporting AR counts correctly (or whether bg is included)
Consider further how background is/should-be handled with area filters (see [skimage.measure](https://scikit-image.org/docs/stable/auto_examples/segmentation/plot_regionprops.html))

@burlen will add a copy-paste of an e-mail conversation

**Comment by burlen** [comment]
resolved

**Pull request closed without merging**
